spring.application.name=xperience-server

# Postgres Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/xperiencedb
spring.datasource.username=xperience
spring.datasource.password=xperience
spring.datasource.driver-class-name=org.postgresql.Driver

# Jwt Properties
app.jwt.secret=test
app.jwt.expiration-ms=60000