spring.application.name=xperience
server.port=8080

# Dev Tools
spring.devtools.restart.enabled = true
spring.devtools.livereload.enabled=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/xperiencedb
spring.datasource.username=xperience
spring.datasource.password=xperience
spring.datasource.driverClassName=org.postgresql.Driver


# JPA Configuration
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
