spring.application.name=xperience-server

# Postgres configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/xperiencedb
spring.datasource.username=xperience
spring.datasource.password=xperience
spring.datasource.driver-class-name=org.postgresql.Driver